/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health and Concurrency Status
         * @description Returns the Watchdog and Semaphore queue saturation limits.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System Online Payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * JWT Session Generation
         * @description Authenticates a user and returns a Galvanic Isolation JWT token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Token payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unified Command Pipeline
         * @description Executes a multi-modal payload through MenirLogos into the Semaphore command bus.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        intent: string;
                        /** @default WEB_UI */
                        origin?: string;
                    };
                };
            };
            responses: {
                /** @description Command Enqueued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Tenant Forgery/Isolation Breach */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Semaphore Exhaustion (30s TTL) */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Tenant
         * @description O Nó principal de Context Isolation.
         */
        Tenant: {
            /** Uid */
            uid: string;
            /** Project */
            project: string;
            /**
             * Labels
             * @default [
             *       "Tenant"
             *     ]
             */
            labels: string[];
            /**
             * Name
             * @description A Enumeração rígida dos Tenants permitidos na arquitetura.
             * @enum {string}
             */
            name: "BECO" | "SANTOS";
        };
        /** User */
        User: {
            /** Uid */
            uid: string;
            /** Project */
            project: string;
            /**
             * Labels
             * @default [
             *       "User",
             *       "Person"
             *     ]
             */
            labels: string[];
            /**
             * Name
             * @description O nome do Usuário.
             */
            name: string;
            /**
             * Email
             * @default null
             */
            email: string | null;
            /**
             * Role
             * @default USER
             * @enum {string}
             */
            role: "ADMIN" | "AUDITOR" | "USER";
        };
        /**
         * Session
         * @description Usado futuramente no JWT parsing para o Zero-Trust Middleware.
         */
        Session: {
            /** Token */
            token: string;
            /**
             * Tenant Id
             * @enum {string}
             */
            tenant_id: "BECO" | "SANTOS";
            /** User Id */
            user_id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** Person */
        Person: {
            /** Uid */
            uid: string;
            /** Project */
            project: string;
            /**
             * Labels
             * @default [
             *       "Person"
             *     ]
             */
            labels: string[];
            /** Name */
            name: string;
            /**
             * Email
             * @default null
             */
            email: string | null;
        };
        /** Organization */
        Organization: {
            /** Uid */
            uid: string;
            /** Project */
            project: string;
            /**
             * Labels
             * @default [
             *       "Organization"
             *     ]
             */
            labels: string[];
            /** Name */
            name: string;
        };
        /** InvoiceLineItem */
        InvoiceLineItem: {
            /**
             * Description
             * @description Descrição clara do item, serviço ou produto.
             */
            description: string;
            /**
             * Gross Amount
             * @description Valor bruto da linha.
             */
            gross_amount: number;
            /**
             * Tva Rate Applied
             * @description Taxa de imposto aplicada à linha (ex: 8.1, 2.6). Se não especificada, deixe nulo.
             * @default null
             */
            tva_rate_applied: number | null;
        };
        /** InvoiceData */
        InvoiceData: {
            /** Uid */
            uid: string;
            /** Project */
            project: string;
            /**
             * Labels
             * @default [
             *       "Invoice",
             *       "Document"
             *     ]
             */
            labels: string[];
            /**
             * Vendor Name
             * @description Nome do fornecedor que emitiu a fatura.
             */
            vendor_name: string;
            /**
             * Vendor Uid
             * @description Número UID Suíço com a extensão de IVA se aplicável (ex: CHE-123.456.789 TVA).
             * @default null
             */
            vendor_uid: string | null;
            /**
             * Vendor Iban
             * @description IBAN suíço ou europeu na fatura.
             * @default null
             */
            vendor_iban: string | null;
            /**
             * Currency
             * @description A moeda oficial do documento.
             * @enum {string}
             */
            currency: "CHF" | "EUR";
            /**
             * Issue Date
             * @description Data de emissão no formato YYYY-MM-DD.
             */
            issue_date: string;
            /**
             * Subtotal
             * @description Soma do valor líquido sem impostos de todas as linhas.
             */
            subtotal: number;
            /**
             * Tip Or Unregulated Amount
             * @description Gorjetas (Pourboire) ou valores não tributados.
             * @default 0
             */
            tip_or_unregulated_amount: number;
            /**
             * Total Amount
             * @description Valor total a pagar exigido no documento.
             */
            total_amount: number;
            /**
             * Items
             * @description Lista com todos os itens extraídos.
             */
            items: components["schemas"]["InvoiceLineItem"][];
            /**
             * Requires Manual Justification
             * @description Flag: Marcar como TRUTH se for um recibo de restaurante ou despesa de representação que exija justificativa do contador.
             * @default false
             */
            requires_manual_justification: boolean;
        };
        /**
         * SystemPersonaPayload
         * @description Strict validation for the System Persona extracted from the Graph
         *     before it initializes the LLM Context Window.
         */
        SystemPersonaPayload: {
            /**
             * Name
             * @description The Persona designation (e.g. DEFAULT_MENIR)
             */
            name: string;
            /**
             * Version
             * @description The semantic version of the Persona
             */
            version: string;
            /**
             * System Prompt
             * @description The actual cognitive directive for the LLM
             */
            system_prompt: string;
        };
        /**
         * Heartbeat
         * @description System internal status check payload.
         */
        Heartbeat: {
            /** Status */
            status: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Memory Usage Mb */
            memory_usage_mb: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
