// Verifica privilégios e roles do usuário atual

SHOW USER neo4j PRIVILEGES;

SHOW ROLE PUBLIC PRIVILEGES AS COMMANDS;

SHOW ROLE admin PRIVILEGES AS COMMANDS;

SHOW ROLE reader PRIVILEGES AS COMMANDS;

SHOW ROLE editor PRIVILEGES AS COMMANDS;
