"""Tests for menir10_export module."""

import json
import tempfile
import unittest
from pathlib import Path

from menir10.menir10_export import load_logs, generate_cypher_interactions


class TestLoadLogs(unittest.TestCase):
    """Test load_logs function."""

    def test_load_logs_from_temp_file(self):
        """Test loading logs from a temporary JSONL file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            log_file = Path(tmpdir) / "test.jsonl"
            
            # Create test entries
            entries = [
                {
                    "interaction_id": "id1",
                    "project_id": "test_a",
                    "intent_profile": "greeting",
                    "created_at": "2025-11-26T00:00:00+00:00",
                    "updated_at": "2025-11-26T00:00:00+00:00",
                    "flags": {},
                },
                {
                    "interaction_id": "id2",
                    "project_id": "test_b",
                    "intent_profile": "query",
                    "created_at": "2025-11-26T00:01:00+00:00",
                    "updated_at": "2025-11-26T00:01:00+00:00",
                    "flags": {"flagX": True},
                },
            ]
            
            # Write entries to JSONL
            with open(log_file, "w", encoding="utf-8") as f:
                for entry in entries:
                    json.dump(entry, f)
                    f.write("\n")
            
            # Load and verify
            loaded = load_logs(log_file)
            
            self.assertEqual(len(loaded), 2)
            project_ids = {entry["project_id"] for entry in loaded}
            self.assertEqual(project_ids, {"test_a", "test_b"})

    def test_load_logs_nonexistent_file(self):
        """Test loading from a file that does not exist."""
        result = load_logs("/nonexistent/path/to/log.jsonl")
        self.assertEqual(result, [])


class TestGenerateCypherInteractions(unittest.TestCase):
    """Test generate_cypher_interactions function."""

    def test_generate_cypher_basic(self):
        """Test Cypher script generation."""
        logs = [
            {
                "project_id": "test_a",
                "intent_profile": "greeting",
            },
            {
                "project_id": "test_b",
                "intent_profile": "query",
            },
        ]
        
        cypher = generate_cypher_interactions(logs)
        
        # Check for expected content
        self.assertIn("CREATE", cypher)
        self.assertIn("PerceptionState", cypher)
        self.assertIn("test_a", cypher)
        self.assertIn("test_b", cypher)
        self.assertIn("// Generated by menir10_export.py", cypher)

    def test_generate_cypher_with_special_chars(self):
        """Test Cypher generation with special characters."""
        logs = [
            {
                "project_id": "proj's",
                "note": "It's working",
            },
        ]
        
        cypher = generate_cypher_interactions(logs)
        
        # Should contain escaped quotes
        self.assertIn("\\'", cypher)
        self.assertIn("CREATE", cypher)


if __name__ == "__main__":
    unittest.main()
