"""Export interaction logs to Cypher format."""

import json
from pathlib import Path
from typing import Iterable, List, Dict, Any

from .menir10_log import LOG_PATH as DEFAULT_LOG_PATH


def load_logs(log_path: Path | str | None = None) -> List[Dict[str, Any]]:
    """Load interactions from JSONL log file.
    
    Args:
        log_path: Path to log file. If None, use DEFAULT_LOG_PATH.
        
    Returns:
        List of log entry dictionaries. Empty list if file does not exist.
    """
    if log_path is None:
        log_path = DEFAULT_LOG_PATH
    
    log_path = Path(log_path)
    
    if not log_path.exists():
        return []
    
    logs = []
    with open(log_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                logs.append(json.loads(line))
    
    return logs


def _format_value(value: Any) -> str:
    """Format a Python value as a Cypher literal.
    
    Args:
        value: Value to format (str, number, bool, or other)
        
    Returns:
        Cypher-formatted string representation
    """
    if isinstance(value, str):
        # Escape single quotes and wrap as Cypher string literal
        escaped = value.replace("'", "\\'")
        return f"'{escaped}'"
    elif isinstance(value, bool):
        # Cypher uses lowercase true/false
        return str(value).lower()
    elif isinstance(value, (int, float)):
        return str(value)
    else:
        # For complex types, serialize to JSON and wrap as string
        json_str = json.dumps(value, ensure_ascii=False)
        escaped = json_str.replace("'", "\\'")
        return f"'{escaped}'"


def generate_cypher_interactions(logs: Iterable[Dict[str, Any]], label: str = "PerceptionState") -> str:
    """Generate Cypher CREATE statements from interaction logs.
    
    Args:
        logs: Iterable of log entry dictionaries
        label: Node label to use (default: "PerceptionState")
        
    Returns:
        Cypher script as a single string
    """
    lines = [
        "// Generated by menir10_export.py",
        "",
    ]
    
    for entry in logs:
        # Build property list
        props = []
        for key, value in entry.items():
            formatted_value = _format_value(value)
            props.append(f"{key}: {formatted_value}")
        
        props_str = ", ".join(props)
        cypher_line = f"CREATE (:{label} {{ {props_str} }});"
        lines.append(cypher_line)
    
    return "\n".join(lines)


def main() -> None:
    """Load logs from default path and export to Cypher file."""
    logs = load_logs()
    
    if not logs:
        print("No logs found. Skipping export.")
        return
    
    cypher_script = generate_cypher_interactions(logs)
    
    # Ensure exports directory exists
    export_dir = Path("exports")
    export_dir.mkdir(parents=True, exist_ok=True)
    
    # Write to file
    export_path = export_dir / "menir10_interactions.cypher"
    with open(export_path, "w", encoding="utf-8") as f:
        f.write(cypher_script)
    
    print(f"Exported {len(logs)} interactions to {export_path}")


if __name__ == "__main__":
    main()
